### ISSUE TITLE
Display Instructions to User

### ISSUE THREAD

**Issue by calexander618** [computationalmystic/RJI-group1#16]
**Is your feature request related to a problem? If so, please describe the problem:**
The user could have issues figuring out where to go on the site to upload/download photos or how to do so.

**Describe the solution you'd like:**
Some sort of how to guide either somewhere on the site or within the mark down on the main page of the repository.

**Comment by AEGuthrie** [comment]
Instructions are currently included with the emails the user receives when their uploaded images are finished. Further instructions are being considered in sort of guide form.

**Comment by sgoggins** [comment]
This is a good idea I would like to see developed!

**Comment by calexander618** [comment]
We have added an alert system and simple instructions: although they are not as comprehensive as they could be, this could easily be fixed if there were more time.
