### ISSUE TITLE
What is happening if I try to upload a 33 gig image? 

### ISSUE THREAD

**Issue by sgoggins** [computationalmystic/RJI-group1#17]
**Describe the bug:**

**To Reproduce:**

**Expected behavior:**

**Screenshots**
![image](https://user-images.githubusercontent.com/379847/57303433-ecb7eb80-70a2-11e9-80da-32d6a7c646cd.png)

**Desktop (please complete the following information):**
- OS: MAC
- Browser: firefox. 

**Additional context**
Some images were not too big. Some were. Am I stuck? I can't delete the ones it says are too big.

**Comment by calexander618** [comment]
This isn't really a bug as much as it is a configuration issue. Previously, large files were not being uploaded with the rest of the submission, but we tweaked Dropzone JS so it can handle files of a larger size.
