### ISSUE TITLE
Graded Photos not visible

### ISSUE THREAD

**Issue by sgoggins** [computationalmystic/RJI-group1#18]
**Describe the bug:**

**To Reproduce:**
1. Uploaded photos to be scored
2. Got emails saying they had been scored. 
3. Links did not work
4. Then I found the downloads link and went there, where two different links appeared, but I got a message saying that the photo had not yet been graded. 

**Expected behavior:**
I expect the photos to be graded when I get the link emailed, and I expect that we will be able to see the grades. And the link will be correct in the email. 

**Screenshots**
Here's the email I got `Your photos have been analyzed! Visit this link to download the scored submission: https://rjimizzou.info/download/6/1`
![image](https://user-images.githubusercontent.com/379847/57304750-84b6d480-70a5-11e9-81d1-5b3da9c3fea8.png)

**Desktop (please complete the following information):**
- OS: MAC
- Browser: Firefox

**Additional context**
I got emails saying my photos were graded. Two issues noted.

**Comment by calexander618** [comment]
This has been fixed, there was an oversight in our DownloadController.php file with some variables within in a string. Upon changing the single quotes to double quotes this problem was solved.
