### ISSUE TITLE
You rated my photo!!! :) 

### ISSUE THREAD

**Issue by sgoggins** [computationalmystic/RJI-group1#5]
AWESOME ... but, um, is it 4.89 out of 5? 10? 

:) 

Thanks!

**Comment by gavin-keli** [comment]
4.89 out of 10
:)

**Comment by calexander618** [comment]
As Gavin said, the score is out of 10. From the data we have in mySQL currently, it seems that good images are rated at about 5.0+ in both metrics, while bad images are rated less than 4.5. There will be some calibration needed to find what images are desirable that do not fall within those ranges. I will update the index.html file to at least represent that the score it out of 10.
